name: Nostalgie
favicon: null
layout_spectrum: 0.75325
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#2c1205'
    - '#f8d31c'
    - '#7d5e17'
    - '#a1883a'
  brandStrength: 0.1875
  lightness: 0.88339434703812
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
