analytics: {}
color:
  brandColors:
    - '#B8C8C8'
    - '#5D2828'
    - '#688098'
    - '#703030'
    - '#000000'
  brandStrength: 0
  lightness: 0.4375
  rhythmicContrast: 0.75
  saturation: 0.3125
cta: {}
layout_spectrum: 0.75325
name: Nostalgie
opengraph: {}
purpose: []
typography_spectrum: 1
