name: Nostalgie
favicon: null
layout_spectrum: 0.4721075380221009
typography_spectrum: 0.032312902389094234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.40173856797628105
  lightness: 0.88339434703812
  saturation: 0.3401247940491885
  rhythmicContrast: 0.2299912218004465
purpose: []
